project:
  type: website

website:
  title: "Portfolio"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: testimonials.qmd
        text: Testimonials

format:
  html:
    theme: cerulean
    css: css/styles.css
    toc: false



