project:
  type: website
  output-dir: docs

website:
  title: "carecodeconnect"
  site-url: https://www.carecodeconnect.io
  description: "Revisioning data science for the age of AI"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - href: testimonials.qmd
        text: Testimonials
      - icon: rss
        href: blog.xml

format:
  html:
    theme:
      light:
        - litera
        - theme.scss
      dark:
        - darkly
        - theme-dark.scss
    highlight-style:
      light: gruvbox-light
      dark: gruvbox-dark
    css: css/styles.css
    toc: false
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&family=IBM+Plex+Mono:ital,wght@0,400;0,500;0,600;1,400&display=swap" rel="stylesheet">



