---
title: "About"
---

Welcome to `care-code-connect`! 🤗

We combine the tools of social science and data science to build solutions to complex social problems.

1. **Decode the matrix of human relations with technology**: by linking computation with interpretation, we tell the human stories behind the data.

2. **Build machine learning solutions to create caring futures**: a data revolution that is equitable, fair, and sustainable. Our solutions are infused with care, ethics, privacy. We are sensitive to cultural, geographical, historical circumstances, social contexts and differences that make a difference.

3. **Apply cutting-edge free and open source technologies to put people at the heart of the data**: creating evidence-based decision-making and actionable 'outsights' to make the world a better place.

In short, we **care**, **code**, **connect**.

Explore our [projects](projects.qmd) to find out more!

This portfolio was made with ❤️ using [Python](https://www.python.org/), [Quarto](https://quarto.org/) and [Shiny](https://shiny.rstudio.com/).

# Recent projects

- Building robust and reliable LLM/SLM AI assistant to help freelancers find high quality gigs (Shoutt).

- Automated data analytics, causal inference, and predictive models for enhancing eco-driving behaviours (Lightfoot).

- Built interactive meditation assistant providing personalised guidance using voice and brain signals for enhanced well-being (Data Science Retreat).

## Skills

- Expertise in scientific research, education, mentoring and project leadership. Skilled in research, model development, deployment, evaluation, and monitoring across the lifecycle of data products.

- Advanced expertise building persuasive technologies to create behaviour change in the health, well-being, and sustainability domains. Deep expertise in causal inference and experimentation and building ML and AI systems for predictive analysis and generation of text, language, and talk-in-interaction, informed by cutting-edge human-computer interaction research on people's use of digital technologies.

- Applies best practices in software engineering - functional and object-oriented programming, testing, version control - to Machine Learning and AI production pipelines at scale. 

- User and product sense with research-based skillset combining conceptual, critical thinking and communication skills with scientific, programming, and engineering skills. 

# Tools

## Programming Languages

- Rust, Python, R, SQL, bash

## Data Science & Analytics

- pandas, polars, matplotlib, plotnine, tidyverse (dplyr, ggplot2)

## Machine Learning

- NumPy, scikit-learn, TensorFlow, PyTorch

## Software Engineering & DevOps

- Documentation (Jupyter, Quarto, Sphinx), version control (git/GitHub), testing (PyTest), CI/CD (GitHub Actions), containerisation (Docker)

## AI Engineering 

- OpenAI API, Codex, Cursor, Ollama, HuggingFace, LangChain, Weights&Biases

## Cloud Infrastructure

- AWS (EC2, S3), Microsoft Azure DevOps, Google Cloud Platform

## Business Intelligence Tools

- Tableau, Power BI, Zoho Analytics, Excel