---
title: "Testimonials"
format: html
toc: true
---

# *Bahar Rezaei*, Data Scientist

> "I had the pleasure of collaborating with Stephen on a project to build a personalized conversational meditation app. Stephen's exceptional people skills, exemplified through strong communication, teamwork, and leadership in an agile environment, were instrumental in the project's success. He demonstrated a deep understanding of product development, skillfully bridging theoretical insights with practical implementation. Stephen not only excels in quick coding and efficient technicality but also brings a positive energy and generous spirit to teamwork, readily sharing his knowledge and ideas. I wholeheartedly recommend Stephen for any data science role."

# *Christian Liedl*, Data Scientist

> "I met Stephen during a data science boot camp, and had the pleasure to work with him on a project to predict housing damage during the 2015 earthquake in Gorkha, Nepal. Stephen has great intuition for what are relevant patterns in data sets. His tremendous experience in data science, data engineering, and statistics was super helpful for guiding decisions about choosing the right machine learning model. Beyond his technical skills, he is a very kind, humble, and emotionally intelligent person and it was simply a joy to collaborate with him!"

# *Duncan Moss*, Clinical Psychologist & Researcher

> "I am a Clinical Psychologist and Researcher with over 30 years experience and have known Stephen for over 10 years. In that time we have collaborated (and I have participated) on a number of projects and I have come to know their abilities very well. Stephen is an extremely capable Researcher with a mastery of a wide range of research skills. In my experience, they are able to work with both data and people very capably. Stephen has a particular ability at synthesising wide ranging data - quantitative and qualitative - and putting these into a clear and coherent context. Their writing skills are extremely advanced in my opinion. I’ve also witnessed Stephen working closely with colleagues and participants, for example creatively organising, hosting and facilitating events with a wide range of people involved. Stephen's calm, mindful and friendly demeanour and quiet leadership is always evident. I have no hesitation in recommending them as a fantastic asset to any organisation." 

# *Joshua Nowak*, Data Scientist

> "I had the pleasure of working with Stephen at Data Science Retreat (DSR) where I got to know him as a skilled data professional and a thoughtful, empathetic human. His curiosity and drive to explore new technologies impressed me the most. Stephen keenly follows the open-source space and always had interesting bits of knowledge to share. For his final project at DSR, he was not afraid to learn and combine multiple complex topics like LLM fine-tuning, EEG-based brain monitoring, and advanced speech processing. As a seasoned social psychologist, Stephen also excels at "zooming out" and considering the societal and business impact of his work. I am excited to see what Stephen creates next!"

# *Krzysztof Buzar*, Python Developer

> "Stephen consistently impressed me with his sharp intellect, technical savvy, and enthusiastic approach to learning. In my opinion, during the courses I took, Stephen always showed remarkable technical proficiency, an aptitude for quickly understanding complicated ideas, and an eagerness to learn throughout the courses. Since I like to teach with the use of anecdotes, it was wonderful to experience the resonance with them! On multiple occasions, Stephen demonstrated the capacity to solve problems creatively and with optimism, which is all one can hope for as a teacher during his classes. In addition to his technical prowess, Stephen is an enthusiastic person who is passionate about SOTA technologies, and I personally see a great future in IT for him."

# *Meg-John Barker*, writer, mentor and associate at *Centre for Transforming Sexuality and Gender*, University of Brighton

> "I consider Stephen to be an exceptional researcher who would be an asset to any organisation. I have known Stephen for over a decade as a friend and colleague. I consider their work to be some of the most important and innovative in the field, and I frequently draw upon it in my own writing. We have also collaborated together on a number of projects. We have conducted and published research together, as well as co-organising several conferences and other events. Most recently, I was a stakeholder/participant on their major funded project: ‘Mapping Mindfulness’. I can therefore speak to Stephen’s abilities, professionalism, communication skills, and qualities as a researcher and colleague. The ‘Mapping Mindfulness’ project employed an innovative participatory co-design, which meant that stakeholder/participants were engaged with in various ways throughout the research process. I certainly found that this approach enabled me to feel invested in the project, with the potential to engage in ways that ensured that the outcomes of the research would be helpful in relation to my own work. In all of their research, Stephen demonstrates clear, enthusiastic and insightful engagement with their stakeholders and participants, and a consistent commitment to ethical principles." 

# *Tristan Behrens*, Data Scientist

> "I met Stephen at a data science boot camp in Berlin, where I was the teacher. What struck me immediately about the fine person that Stephen is, is his interdisciplinary nature, which is an asset for any serious undertaking in the fields we so love (Data Science and AI). Stephen is perfectly capable of implementing his ideas in a very thorough way. I was impressed by the project he was working on."
