{
  "hash": "596a7f45c8d26140e352e4479a93a222",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"MapMind (Part III): Digital Divides: Mindfulness Teaching & Technology\"\nexecute:\n  warning: false\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the code\"\n    toc: true\nnumber-sections: true\njupyter: python3\n---\n\n::: {#f63b3291 .cell execution_count=1}\n``` {.python .cell-code}\n# Import libraries\nimport numpy as np\nimport pandas as pd\nimport itertools\nimport statsmodels.formula.api as smf\nimport statsmodels.api as sm\nfrom scipy.stats import chi2_contingency\nfrom prettytable import PrettyTable\nimport seaborn as sns\nimport matplotlib.pyplot as plt\nimport plotly.graph_objects as go\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import classification_report, confusion_matrix, roc_auc_score\nfrom sklearn.preprocessing import LabelEncoder, OneHotEncoder\nfrom sklearn.impute import SimpleImputer\nfrom imblearn.over_sampling import SMOTE\n```\n:::\n\n\n# Executive Summary\n\nThe final part of the MapMind project looks at how mindfulness teachers relate to technology, and uses predictive modeling using **Chi-Squared tests** and **logistic regression** to identify the factors that predict whether mindfulness teachers engage in online teaching based on several features, including gender, years of teaching experience, whether they hold a management position, and their nationality.\n\nWe ask the following research question: \n\n- What demographic factors influence use of **technology**, use of a **professional website**, and **online teaching** of mindfulness?\n\n# Data Science Tools\n\nIn this part of the project, I use numpy and pandas for data analysis; SciPy, statsmodels, and Scikit-Learn for statistical analysis; and PlotlyExpress for data visualisation. I use Synthetic Minority Over-sampling Technique (SMOTE) to increase the number of instances in the dataset.\n\n# Findings\n\n- Majority of mindfulness teachers start to teach mindfulness between 2012-2014.\n- Majority use technology, have a website, but had not taught online.\n\nWe found significant correlations in how demographic and social factors influence technology usage, use of a professional website, and online teaching. This is crucial for understanding diverse needs in the digital landscape of mindfulness and wellness teaching.\n\nWhen we analysed the factors which most significantly influence mindfulness teaching, we found:\n\n- Formal education level is a more significant predictor of technology use in mindfulness teaching than age.\n\n## Majority start to teach mindfulness between 2012-2014\n\nIn the analysis of the `year_started` variable from a mindfulness teaching survey, Python libraries `pandas`, `prettytable`, `seaborn`, and `matplotlib.pyplot` were employed. The survey data revealed that among `722` respondents, the average start year of teaching mindfulness was `2012`, with a standard deviation of `6` years, ranging from `1974` to `2019`. The median start year was `2014`, indicating a more recent trend in mindfulness teaching. \n\nComplementing these statistics, a **violin plot** was generated to visualize the distribution of the start years. This plot not only confirmed the central tendency and spread captured by the numerical data but also provided a deeper insight into the density and distribution patterns of the years when respondents began their mindfulness teaching journey. The combined use of descriptive statistics and the violin plot offers a comprehensive understanding of the temporal trends in mindfulness teaching among the survey participants.\n\nOverall, our participants start to teach mindfulness between 1974 and 2019, with `50%` starting to teach from `2014`, and the mean average starting to teach in `2012`. These years correspond with the development of popular technologies - such as computers, the internet, and mobile phones. But while there are a substantial number of participants who start teaching mindfulness in the past `10` years in particular, we should remember that **correlation is not causation**. The rise of mindfulness teaching might be correlated with the rise of technology, rather than caused by the rise of technology.\n\n::: {#e58101d0 .cell execution_count=2}\n``` {.python .cell-code}\n# Load the survey dataframe\nsurvey = pd.read_pickle('data/tidied_survey.pkl')\n\n# Remove rows with NA from the 'year_started' column\nsurvey_clean = survey.dropna(subset=[\"year_started\"])\n\n# Generate descriptive statistics for 'year_started'\ndescriptive_stats = survey_clean['year_started'].describe()\n\n# Round the mean and convert all statistics to integers\ndescriptive_stats_rounded = descriptive_stats.round().astype(int)\n\n# Prepare data for the table\ncells_data = {\n    \"Statistic\": descriptive_stats_rounded.index,\n    \"Value\": descriptive_stats_rounded.values\n}\n\n# Create the table\nfig = go.Figure(data=[go.Table(\n    header=dict(values=[\"Statistic\", \"Value\"],\n                fill_color='lightgrey',\n                align='left',\n                font=dict(color='black', size=12)),\n    cells=dict(values=[cells_data[k] for k in cells_data.keys()],\n               fill_color='white',\n               align='left',\n               font=dict(color='black', size=11),\n               height=30)  # Smaller height for rows\n)])\n\nfig.update_layout(\n    title_text='Year Started Teaching Mindfulness',\n    title_x=0.5,\n    title_font=dict(size=14, family=\"Verdana\"),\n    paper_bgcolor='white',\n    plot_bgcolor='white',\n    margin=dict(l=20, r=20, t=50, b=20)  # Adjusted margins to center the table while keeping title\n)\n\n# Set the size of the table\nfig.update_layout(width=500, height=300)\n\nfig.show()\n\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.4.0.min.js\" integrity=\"sha256-KEmPoupLpFyGMyGAiOsiNDbKDKAvxXAn/W+oQa0ZAfk=\" crossorigin=\"anonymous\"></script>                <div id=\"42b24e62-7ee7-410b-9955-9820ebc668b0\" class=\"plotly-graph-div\" style=\"height:300px; width:500px;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"42b24e62-7ee7-410b-9955-9820ebc668b0\")) {                    Plotly.newPlot(                        \"42b24e62-7ee7-410b-9955-9820ebc668b0\",                        [{\"cells\":{\"align\":\"left\",\"fill\":{\"color\":\"white\"},\"font\":{\"color\":\"black\",\"size\":11},\"height\":30,\"values\":[[\"count\",\"mean\",\"std\",\"min\",\"25%\",\"50%\",\"75%\",\"max\"],[722,2012,6,1974,2011,2014,2016,2019]]},\"header\":{\"align\":\"left\",\"fill\":{\"color\":\"lightgrey\"},\"font\":{\"color\":\"black\",\"size\":12},\"values\":[\"Statistic\",\"Value\"]},\"type\":\"table\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"title\":{\"font\":{\"size\":14,\"family\":\"Verdana\"},\"text\":\"Year Started Teaching Mindfulness\",\"x\":0.5},\"margin\":{\"l\":20,\"r\":20,\"t\":50,\"b\":20},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"white\",\"width\":500,\"height\":300},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('42b24e62-7ee7-410b-9955-9820ebc668b0');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n:::\n:::\n\n\n::: {#f436fba4 .cell execution_count=3}\n``` {.python .cell-code}\n# Load the survey dataframe\nsurvey = pd.read_pickle('data/tidied_survey.pkl')\n\n# Remove rows with NA from the 'year_started' column\nsurvey_clean = survey.dropna(subset=[\"year_started\"])\n\n# Create a violin plot using seaborn for the 'year_started' variable\nplt.figure(figsize=(10, 6))\nsns.violinplot(data=survey_clean, x=\"year_started\", inner=\"quartile\")\n\n# Customize the plot\nplt.title('Distribution of Year Started Teaching')\nplt.xlabel('Year Started Teaching')\nplt.grid(True)\nsns.set_style(\"whitegrid\")\n\n# Show the plot\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](mapmind_technology_files/figure-html/cell-4-output-1.png){width=768 height=521}\n:::\n:::\n\n\n## Majority use technology, have a website, but had not taught online\n\nWe found some interesting contradictions in our data relating to how our participants engage with technology. \n\n- The majority of our participants **use technologies when teaching mindfulness**. These technologies include smartphone apps, books, compact discs, course notes, MP3/podcasts, posters/PowerPoint, physical props such as foot items or musical instruments (excluding chairs/cushions), websites, video clips, flipcharts.\n\n- The majority **have a professional website** for their mindfulness work.\n\n- The majority **had never taught mindfulness online**. \n\nThe following code analyses our participants' use of technology, professional websites, and online teaching. `Pandas` is used for data manipulation and `Plotly Express` for generating the graph. In the results, a significant majority (`91.48%`, n=`644`) of participants use technology in their teaching. Regarding professional website usage, a majority (`60.31%`, n=`392`) have one, while `39.69%` (n=`258`) do not. \n\n::: {#b0bb1ee3 .cell execution_count=4}\n``` {.python .cell-code}\nimport pandas as pd\nimport plotly.express as px\n\n# Load the survey dataframe\nsurvey = pd.read_pickle('data/tidied_survey.pkl')\n\n# Convert data to long format for faceting\nsurvey_long = survey.melt(id_vars=[], value_vars=['technology', 'website', 'online_teaching'], \n                          var_name='demographic', value_name='value')\n\n# Calculate frequency for each value within each demographic\nsurvey_freq = survey_long.groupby(['demographic', 'value'], observed=True).size().reset_index(name='freq')\n\n# Remove NA values\nsurvey_freq = survey_freq.dropna(subset=['value'])\n\n# Convert the 'value' column to a category\nsurvey_freq['value'] = survey_freq['value'].astype('category')\n\n# Arrange by demographic and frequency\nsurvey_freq = survey_freq.sort_values(by=['demographic', 'freq'], ascending=[True, True])\n\n# Calculate percentage\nsurvey_freq['percentage'] = survey_freq.groupby('demographic')['freq'].transform(lambda x: x / x.sum() * 100)\n\n# Plot with Plotly Express\nfig = px.bar(survey_freq, x='value', y='percentage', color='value', facet_col='demographic', \n             labels={'value': 'Value', 'percentage': 'Percentage'}, \n             category_orders={'demographic': ['technology', 'website', 'online_teaching']},\n             height=400, width=1000,\n             hover_data={'freq': ':.0f', 'percentage': ':.2f%'})\n\n# Update layout to match the aesthetics\nfig.update_layout(\n    title_text=\"Mindfulness Teachers' Use of Technologies\",\n    title_x=0.5,\n    title_font=dict(size=14, family=\"Verdana\"),\n    showlegend=False,\n    paper_bgcolor='white',\n    plot_bgcolor='white'\n)\n\n# Update axes labels\nfig.for_each_annotation(lambda a: a.update(text=a.text.split(\"=\")[-1]))\nfig.update_xaxes(showticklabels=True)\nfig.update_yaxes(title='Percentage')\n\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.4.0.min.js\" integrity=\"sha256-KEmPoupLpFyGMyGAiOsiNDbKDKAvxXAn/W+oQa0ZAfk=\" crossorigin=\"anonymous\"></script>                <div id=\"4a70e873-e3e0-432e-82da-a288effa2b37\" class=\"plotly-graph-div\" style=\"height:400px; width:1000px;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"4a70e873-e3e0-432e-82da-a288effa2b37\")) {                    Plotly.newPlot(                        \"4a70e873-e3e0-432e-82da-a288effa2b37\",                        [{\"customdata\":{\"dtype\":\"i2\",\"bdata\":\"hAI=\",\"shape\":\"1, 1\"},\"hovertemplate\":\"Value=%{x}\\u003cbr\\u003edemographic=technology\\u003cbr\\u003ePercentage=%{y:.2f%}\\u003cbr\\u003efreq=%{customdata[0]:.0f}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"Yes\",\"marker\":{\"color\":\"#636efa\",\"pattern\":{\"shape\":\"\"}},\"name\":\"Yes\",\"orientation\":\"v\",\"showlegend\":true,\"textposition\":\"auto\",\"x\":[\"Yes\"],\"xaxis\":\"x\",\"y\":{\"dtype\":\"f8\",\"bdata\":\"L7roooveVkA=\"},\"yaxis\":\"y\",\"type\":\"bar\"},{\"customdata\":{\"dtype\":\"i1\",\"bdata\":\"PA==\",\"shape\":\"1, 1\"},\"hovertemplate\":\"Value=%{x}\\u003cbr\\u003edemographic=technology\\u003cbr\\u003ePercentage=%{y:.2f%}\\u003cbr\\u003efreq=%{customdata[0]:.0f}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"No\",\"marker\":{\"color\":\"#EF553B\",\"pattern\":{\"shape\":\"\"}},\"name\":\"No\",\"orientation\":\"v\",\"showlegend\":true,\"textposition\":\"auto\",\"x\":[\"No\"],\"xaxis\":\"x\",\"y\":{\"dtype\":\"f8\",\"bdata\":\"iy666KILIUA=\"},\"yaxis\":\"y\",\"type\":\"bar\"},{\"customdata\":{\"dtype\":\"i2\",\"bdata\":\"iAE=\",\"shape\":\"1, 1\"},\"hovertemplate\":\"Value=%{x}\\u003cbr\\u003edemographic=website\\u003cbr\\u003ePercentage=%{y:.2f%}\\u003cbr\\u003efreq=%{customdata[0]:.0f}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"Yes\",\"marker\":{\"color\":\"#636efa\",\"pattern\":{\"shape\":\"\"}},\"name\":\"Yes\",\"orientation\":\"v\",\"showlegend\":false,\"textposition\":\"auto\",\"x\":[\"Yes\"],\"xaxis\":\"x2\",\"y\":{\"dtype\":\"f8\",\"bdata\":\"dmIndmInTkA=\"},\"yaxis\":\"y2\",\"type\":\"bar\"},{\"customdata\":{\"dtype\":\"i2\",\"bdata\":\"AgE=\",\"shape\":\"1, 1\"},\"hovertemplate\":\"Value=%{x}\\u003cbr\\u003edemographic=website\\u003cbr\\u003ePercentage=%{y:.2f%}\\u003cbr\\u003efreq=%{customdata[0]:.0f}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"No\",\"marker\":{\"color\":\"#EF553B\",\"pattern\":{\"shape\":\"\"}},\"name\":\"No\",\"orientation\":\"v\",\"showlegend\":false,\"textposition\":\"auto\",\"x\":[\"No\"],\"xaxis\":\"x2\",\"y\":{\"dtype\":\"f8\",\"bdata\":\"ip3YiZ3YQ0A=\"},\"yaxis\":\"y2\",\"type\":\"bar\"},{\"customdata\":{\"dtype\":\"i2\",\"bdata\":\"uAA=\",\"shape\":\"1, 1\"},\"hovertemplate\":\"Value=%{x}\\u003cbr\\u003edemographic=online_teaching\\u003cbr\\u003ePercentage=%{y:.2f%}\\u003cbr\\u003efreq=%{customdata[0]:.0f}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"Yes\",\"marker\":{\"color\":\"#636efa\",\"pattern\":{\"shape\":\"\"}},\"name\":\"Yes\",\"orientation\":\"v\",\"showlegend\":false,\"textposition\":\"auto\",\"x\":[\"Yes\"],\"xaxis\":\"x3\",\"y\":{\"dtype\":\"f8\",\"bdata\":\"JP31XMWyOUA=\"},\"yaxis\":\"y3\",\"type\":\"bar\"},{\"customdata\":{\"dtype\":\"i2\",\"bdata\":\"FAI=\",\"shape\":\"1, 1\"},\"hovertemplate\":\"Value=%{x}\\u003cbr\\u003edemographic=online_teaching\\u003cbr\\u003ePercentage=%{y:.2f%}\\u003cbr\\u003efreq=%{customdata[0]:.0f}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"No\",\"marker\":{\"color\":\"#EF553B\",\"pattern\":{\"shape\":\"\"}},\"name\":\"No\",\"orientation\":\"v\",\"showlegend\":false,\"textposition\":\"auto\",\"x\":[\"No\"],\"xaxis\":\"x3\",\"y\":{\"dtype\":\"f8\",\"bdata\":\"t4DCqE6TUkA=\"},\"yaxis\":\"y3\",\"type\":\"bar\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"xaxis\":{\"anchor\":\"y\",\"domain\":[0.0,0.31999999999999995],\"title\":{\"text\":\"Value\"},\"categoryorder\":\"array\",\"categoryarray\":[\"Yes\",\"No\"],\"showticklabels\":true},\"yaxis\":{\"anchor\":\"x\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Percentage\"}},\"xaxis2\":{\"anchor\":\"y2\",\"domain\":[0.33999999999999997,0.6599999999999999],\"matches\":\"x\",\"title\":{\"text\":\"Value\"},\"categoryorder\":\"array\",\"categoryarray\":[\"Yes\",\"No\"],\"showticklabels\":true},\"yaxis2\":{\"anchor\":\"x2\",\"domain\":[0.0,1.0],\"matches\":\"y\",\"showticklabels\":false,\"title\":{\"text\":\"Percentage\"}},\"xaxis3\":{\"anchor\":\"y3\",\"domain\":[0.6799999999999999,0.9999999999999999],\"matches\":\"x\",\"title\":{\"text\":\"Value\"},\"categoryorder\":\"array\",\"categoryarray\":[\"Yes\",\"No\"],\"showticklabels\":true},\"yaxis3\":{\"anchor\":\"x3\",\"domain\":[0.0,1.0],\"matches\":\"y\",\"showticklabels\":false,\"title\":{\"text\":\"Percentage\"}},\"annotations\":[{\"font\":{},\"showarrow\":false,\"text\":\"technology\",\"x\":0.15999999999999998,\"xanchor\":\"center\",\"xref\":\"paper\",\"y\":1.0,\"yanchor\":\"bottom\",\"yref\":\"paper\"},{\"font\":{},\"showarrow\":false,\"text\":\"website\",\"x\":0.49999999999999994,\"xanchor\":\"center\",\"xref\":\"paper\",\"y\":1.0,\"yanchor\":\"bottom\",\"yref\":\"paper\"},{\"font\":{},\"showarrow\":false,\"text\":\"online_teaching\",\"x\":0.8399999999999999,\"xanchor\":\"center\",\"xref\":\"paper\",\"y\":1.0,\"yanchor\":\"bottom\",\"yref\":\"paper\"}],\"legend\":{\"title\":{\"text\":\"Value\"},\"tracegroupgap\":0},\"barmode\":\"relative\",\"height\":400,\"width\":1000,\"title\":{\"font\":{\"size\":14,\"family\":\"Verdana\"},\"text\":\"Mindfulness Teachers' Use of Technologies\",\"x\":0.5},\"showlegend\":false,\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"white\"},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('4a70e873-e3e0-432e-82da-a288effa2b37');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n:::\n:::\n\n\nAs for online teaching, a larger proportion (`74.30%`, n=`532`) have not taught mindfulness online, while `25.70%` (n=`184`) have. These statistics provide insights into the digital engagement of mindfulness teachers, highlighting a strong inclination towards using technology and websites, but less so for online teaching.\n\n::: {#a760ad65 .cell execution_count=5}\n``` {.python .cell-code}\nimport pandas as pd\nimport plotly.express as px\nimport plotly.graph_objects as go\n\n# Load the survey dataframe\nsurvey = pd.read_pickle('data/tidied_survey.pkl')\n\ndef plot_bar(data, var_name, title):\n    # Ensure the variable is categorical\n    data[var_name] = pd.Categorical(data[var_name])\n\n    # Filter out missing values\n    filtered_data = data.dropna(subset=[var_name])\n\n    # Count occurrences with observed=True\n    count_data = filtered_data.groupby(var_name, observed=True).size().reset_index(name='n')\n\n    # Sort by frequency in descending order\n    count_data = count_data.sort_values(by='n', ascending=False)\n\n    # Create a bar plot\n    fig = px.bar(count_data, x='n', y=var_name, orientation='h', \n                 color=var_name, title=title, \n                 labels={'n': 'Frequency'})\n    fig.update_layout(showlegend=False, template='plotly_white')\n\n    return fig, count_data\n\n# Generate plot and frequency data for online_n variable\np, freq_data = plot_bar(survey, 'online_n', 'Number of Students Taught Online')\n\n# Calculate percentages for the table\ntotal_count = freq_data['n'].sum()\nfreq_data['Percentage'] = (freq_data['n'] / total_count) * 100\n\n# Create a Plotly table\nfig_table = go.Figure(data=[go.Table(\n    header=dict(values=[\"Value\", \"Frequency\", \"Percentage\"],\n                fill_color='paleturquoise',\n                align='left'),\n    cells=dict(values=[freq_data['online_n'], freq_data['n'], freq_data['Percentage'].apply(lambda x: f\"{x:.2f}%\")],\n               fill_color='lavender',\n               align='left'))\n])\n\n# Add title to the table\nfig_table.update_layout(title_text=\"Number of Students Taught Online\", title_x=0.5)\n\n# Display the Plotly table\nfig_table.show()\n\n# Display the bar plot\np.show()\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.4.0.min.js\" integrity=\"sha256-KEmPoupLpFyGMyGAiOsiNDbKDKAvxXAn/W+oQa0ZAfk=\" crossorigin=\"anonymous\"></script>                <div id=\"51c2b7c0-bba0-4891-9454-a17a66eda767\" class=\"plotly-graph-div\" style=\"height:525px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"51c2b7c0-bba0-4891-9454-a17a66eda767\")) {                    Plotly.newPlot(                        \"51c2b7c0-bba0-4891-9454-a17a66eda767\",                        [{\"cells\":{\"align\":\"left\",\"fill\":{\"color\":\"lavender\"},\"values\":[[\"0\",\"1-5\",\"More than 100\",\"21-50\",\"6-10\",\"51-100\",\"11-20\"],[455,67,62,36,35,33,28],[\"63.55%\",\"9.36%\",\"8.66%\",\"5.03%\",\"4.89%\",\"4.61%\",\"3.91%\"]]},\"header\":{\"align\":\"left\",\"fill\":{\"color\":\"paleturquoise\"},\"values\":[\"Value\",\"Frequency\",\"Percentage\"]},\"type\":\"table\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"title\":{\"text\":\"Number of Students Taught Online\",\"x\":0.5}},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('51c2b7c0-bba0-4891-9454-a17a66eda767');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.4.0.min.js\" integrity=\"sha256-KEmPoupLpFyGMyGAiOsiNDbKDKAvxXAn/W+oQa0ZAfk=\" crossorigin=\"anonymous\"></script>                <div id=\"660e91d4-7856-4864-9c93-98804af6db82\" class=\"plotly-graph-div\" style=\"height:525px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"660e91d4-7856-4864-9c93-98804af6db82\")) {                    Plotly.newPlot(                        \"660e91d4-7856-4864-9c93-98804af6db82\",                        [{\"hovertemplate\":\"online_n=%{y}\\u003cbr\\u003eFrequency=%{x}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"0\",\"marker\":{\"color\":\"#636efa\",\"pattern\":{\"shape\":\"\"}},\"name\":\"0\",\"orientation\":\"h\",\"showlegend\":true,\"textposition\":\"auto\",\"x\":{\"dtype\":\"i2\",\"bdata\":\"xwE=\"},\"xaxis\":\"x\",\"y\":[\"0\"],\"yaxis\":\"y\",\"type\":\"bar\"},{\"hovertemplate\":\"online_n=%{y}\\u003cbr\\u003eFrequency=%{x}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"1-5\",\"marker\":{\"color\":\"#EF553B\",\"pattern\":{\"shape\":\"\"}},\"name\":\"1-5\",\"orientation\":\"h\",\"showlegend\":true,\"textposition\":\"auto\",\"x\":{\"dtype\":\"i1\",\"bdata\":\"Qw==\"},\"xaxis\":\"x\",\"y\":[\"1-5\"],\"yaxis\":\"y\",\"type\":\"bar\"},{\"hovertemplate\":\"online_n=%{y}\\u003cbr\\u003eFrequency=%{x}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"More than 100\",\"marker\":{\"color\":\"#00cc96\",\"pattern\":{\"shape\":\"\"}},\"name\":\"More than 100\",\"orientation\":\"h\",\"showlegend\":true,\"textposition\":\"auto\",\"x\":{\"dtype\":\"i1\",\"bdata\":\"Pg==\"},\"xaxis\":\"x\",\"y\":[\"More than 100\"],\"yaxis\":\"y\",\"type\":\"bar\"},{\"hovertemplate\":\"online_n=%{y}\\u003cbr\\u003eFrequency=%{x}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"21-50\",\"marker\":{\"color\":\"#ab63fa\",\"pattern\":{\"shape\":\"\"}},\"name\":\"21-50\",\"orientation\":\"h\",\"showlegend\":true,\"textposition\":\"auto\",\"x\":{\"dtype\":\"i1\",\"bdata\":\"JA==\"},\"xaxis\":\"x\",\"y\":[\"21-50\"],\"yaxis\":\"y\",\"type\":\"bar\"},{\"hovertemplate\":\"online_n=%{y}\\u003cbr\\u003eFrequency=%{x}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"6-10\",\"marker\":{\"color\":\"#FFA15A\",\"pattern\":{\"shape\":\"\"}},\"name\":\"6-10\",\"orientation\":\"h\",\"showlegend\":true,\"textposition\":\"auto\",\"x\":{\"dtype\":\"i1\",\"bdata\":\"Iw==\"},\"xaxis\":\"x\",\"y\":[\"6-10\"],\"yaxis\":\"y\",\"type\":\"bar\"},{\"hovertemplate\":\"online_n=%{y}\\u003cbr\\u003eFrequency=%{x}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"51-100\",\"marker\":{\"color\":\"#19d3f3\",\"pattern\":{\"shape\":\"\"}},\"name\":\"51-100\",\"orientation\":\"h\",\"showlegend\":true,\"textposition\":\"auto\",\"x\":{\"dtype\":\"i1\",\"bdata\":\"IQ==\"},\"xaxis\":\"x\",\"y\":[\"51-100\"],\"yaxis\":\"y\",\"type\":\"bar\"},{\"hovertemplate\":\"online_n=%{y}\\u003cbr\\u003eFrequency=%{x}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"11-20\",\"marker\":{\"color\":\"#FF6692\",\"pattern\":{\"shape\":\"\"}},\"name\":\"11-20\",\"orientation\":\"h\",\"showlegend\":true,\"textposition\":\"auto\",\"x\":{\"dtype\":\"i1\",\"bdata\":\"HA==\"},\"xaxis\":\"x\",\"y\":[\"11-20\"],\"yaxis\":\"y\",\"type\":\"bar\"}],                        {\"template\":{\"data\":{\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"white\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"white\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"#C8D4E3\",\"linecolor\":\"#C8D4E3\",\"minorgridcolor\":\"#C8D4E3\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"#C8D4E3\",\"linecolor\":\"#C8D4E3\",\"minorgridcolor\":\"#C8D4E3\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"choropleth\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"type\":\"choropleth\"}],\"contourcarpet\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"type\":\"contourcarpet\"}],\"contour\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"contour\"}],\"heatmap\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"heatmap\"}],\"histogram2dcontour\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"histogram2dcontour\"}],\"histogram2d\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"histogram2d\"}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"mesh3d\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"type\":\"mesh3d\"}],\"parcoords\":[{\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"parcoords\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}],\"scatter3d\":[{\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scatter3d\"}],\"scattercarpet\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattercarpet\"}],\"scattergeo\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattergeo\"}],\"scattergl\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattergl\"}],\"scattermapbox\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattermapbox\"}],\"scattermap\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattermap\"}],\"scatterpolargl\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scatterpolargl\"}],\"scatterpolar\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scatterpolar\"}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"scatterternary\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scatterternary\"}],\"surface\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"surface\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}]},\"layout\":{\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"autotypenumbers\":\"strict\",\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]],\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]},\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"geo\":{\"bgcolor\":\"white\",\"lakecolor\":\"white\",\"landcolor\":\"white\",\"showlakes\":true,\"showland\":true,\"subunitcolor\":\"#C8D4E3\"},\"hoverlabel\":{\"align\":\"left\"},\"hovermode\":\"closest\",\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"white\",\"polar\":{\"angularaxis\":{\"gridcolor\":\"#EBF0F8\",\"linecolor\":\"#EBF0F8\",\"ticks\":\"\"},\"bgcolor\":\"white\",\"radialaxis\":{\"gridcolor\":\"#EBF0F8\",\"linecolor\":\"#EBF0F8\",\"ticks\":\"\"}},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"white\",\"gridcolor\":\"#DFE8F3\",\"gridwidth\":2,\"linecolor\":\"#EBF0F8\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"#EBF0F8\"},\"yaxis\":{\"backgroundcolor\":\"white\",\"gridcolor\":\"#DFE8F3\",\"gridwidth\":2,\"linecolor\":\"#EBF0F8\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"#EBF0F8\"},\"zaxis\":{\"backgroundcolor\":\"white\",\"gridcolor\":\"#DFE8F3\",\"gridwidth\":2,\"linecolor\":\"#EBF0F8\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"#EBF0F8\"}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"ternary\":{\"aaxis\":{\"gridcolor\":\"#DFE8F3\",\"linecolor\":\"#A2B1C6\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"#DFE8F3\",\"linecolor\":\"#A2B1C6\",\"ticks\":\"\"},\"bgcolor\":\"white\",\"caxis\":{\"gridcolor\":\"#DFE8F3\",\"linecolor\":\"#A2B1C6\",\"ticks\":\"\"}},\"title\":{\"x\":0.05},\"xaxis\":{\"automargin\":true,\"gridcolor\":\"#EBF0F8\",\"linecolor\":\"#EBF0F8\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"#EBF0F8\",\"zerolinewidth\":2},\"yaxis\":{\"automargin\":true,\"gridcolor\":\"#EBF0F8\",\"linecolor\":\"#EBF0F8\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"#EBF0F8\",\"zerolinewidth\":2}}},\"xaxis\":{\"anchor\":\"y\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Frequency\"}},\"yaxis\":{\"anchor\":\"x\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"online_n\"},\"categoryorder\":\"array\",\"categoryarray\":[\"11-20\",\"51-100\",\"6-10\",\"21-50\",\"More than 100\",\"1-5\",\"0\"]},\"legend\":{\"title\":{\"text\":\"online_n\"},\"tracegroupgap\":0},\"title\":{\"text\":\"Number of Students Taught Online\"},\"barmode\":\"relative\",\"showlegend\":false},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('660e91d4-7856-4864-9c93-98804af6db82');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n:::\n:::\n\n\n## What factors predict mindfulness teaching?\n\nStatistical tests were conducted to find out the factors which significantly predict mindfulness teaching. \n\n**Chi-Squared tests** were conducted to identify significant relations between pairs of variables. The significant results are visualised below using an interactive scatter plot. \n\nThe significant results are then displayed in a Plotly Express table sorted by Chi-Squared statistic, which indicates the strength of the significant relationship.\n\n### Predictors\n\n- Age (`age`)\n- Gender (`gender`)\n- Nations where mindfulness is taught (`nations`)\n- Ethnicity (`ethnicity`)\n- Sexuality (`sexuality`)\n- Disability (`disability`)\n- Employment (`employment_other_type`)\n- Formal Education (`formal_education`)\n- Management (`management`)\n- Supervise Employees (`supervise_emp`)\n- Social Class (`social_class`)\n- Year Started Teaching (can act as either predictor or outcome variable) (`year_started`)\n\n### Outcomes\n\n- Technology (`technology`)\n- Website (`website`)\n- Online Teaching (`online_teaching`)\n- Number of Students Taught Online (`online_n`)\n\n### Significant Predictors and Outcomes\n\nWe conducted in-depth analyses of the predictor-and-outcome pairs which are significantly related. This report focuses on the factors which influence mindfulness teaching in relation to technology. The rest of the report summarises the in-depth analyes of the following significantly related factors.\n\nAge and use of a professional website\nAge and use of technology\n\nFormal education and use of technology\n\nGender and online teaching\nGender and number of students taught online\n\nManagement role and online teaching\nManagement role and number of students taught online\nManagement role and use of a professional website\n\nNations where mindfulness is taught and number of students taught online\nNations where mindfulness is taught and online teaching\nNations where mindfulness is taught and use of a professional website\n\nYear started teaching and number of studens taught online\nYear started teaching and online teaching\nYear started teaching and use of a professional website\n\n::: {#80d2abfb .cell execution_count=6}\n``` {.python .cell-code}\n# Load the survey dataframe\nsurvey_social_class_merged = pd.read_pickle('data/survey_social_class_merged.pkl')\n\n# Define independent and dependent variables\nindependent_vars = ['age', 'gender', 'nations', 'ethnicity', 'sexuality', 'disability', \n                    'employment_other_type', 'formal_education', 'management', 'supervise_emp', 'social_class']\ndependent_vars = ['technology', 'website', 'online_teaching', 'online_n']\nyear_started = ['year_started']  # can act as both IV and DV\n\n# Function to perform chi-squared tests and return results as a DataFrame\ndef perform_chi_squared_tests(data):\n    results = []\n\n    # Create all unique pairs of IVs and DVs, including year_started as both\n    for var1, var2 in itertools.product(independent_vars + year_started, dependent_vars + year_started):\n        if var1 != var2:\n            # Drop NaN values separately for the variables being tested\n            data_cleaned = data.dropna(subset=[var1, var2])\n\n            # Conduct chi-squared test\n            table = pd.crosstab(data_cleaned[var1], data_cleaned[var2])\n            chi2_stat, p_val, dof, _ = chi2_contingency(table)\n\n            # Check if the relationship is significant (using a threshold, e.g., 0.05)\n            if p_val < 0.05:\n                # Store results in list\n                results.append([f\"{var1.capitalize()} vs {var2.capitalize()}\",\n                                chi2_stat, dof, p_val, len(data) - len(data_cleaned),\n                                f\"{var1}: {data_cleaned[var1].nunique()}, {var2}: {data_cleaned[var2].nunique()}\"])\n\n    # Convert results to DataFrame\n    results_df = pd.DataFrame(results, columns=[\"Test\", \"Chi-Squared Statistic\", \"Degrees of Freedom\", \"P-Value\", \"NaNs Dropped\", \"Unique Cases\"])\n\n    # Sort results by chi-squared statistic (descending)\n    results_df.sort_values(by=\"Chi-Squared Statistic\", ascending=False, inplace=True)\n\n    return results_df\n\n# Perform chi-squared tests\nsignificant_results_df = perform_chi_squared_tests(survey_social_class_merged)\n\n# Use Plotly Express to create an interactive scatter plot\nfig = px.scatter(significant_results_df, x=\"Test\", y=\"Chi-Squared Statistic\", \n                 size=\"Chi-Squared Statistic\", color=\"P-Value\", \n                 hover_data=[\"Degrees of Freedom\", \"NaNs Dropped\", \"Unique Cases\"],\n                 title=\"Chi-Squared Test Results: Tests vs Chi-Squared Statistic\",\n                 labels={\"Test\": \"Test\", \"Chi-Squared Statistic\": \"Chi-Squared Statistic\", \"P-Value\": \"P-Value\"},\n                 category_orders={\"Test\": significant_results_df[\"Test\"]})  # Order x-axis based on sorted Test names\nfig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.4.0.min.js\" integrity=\"sha256-KEmPoupLpFyGMyGAiOsiNDbKDKAvxXAn/W+oQa0ZAfk=\" crossorigin=\"anonymous\"></script>                <div id=\"24be2fd1-05a4-49d2-950d-d737a4fcd497\" class=\"plotly-graph-div\" style=\"height:525px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"24be2fd1-05a4-49d2-950d-d737a4fcd497\")) {                    Plotly.newPlot(                        \"24be2fd1-05a4-49d2-950d-d737a4fcd497\",                        [{\"customdata\":[[124,56,\"nations: 5, year_started: 32\"],[186,52,\"year_started: 32, online_n: 7\"],[93,111,\"gender: 4, year_started: 32\"],[93,112,\"formal_education: 4, year_started: 32\"],[72,338,\"social_class: 4, year_started: 25\"],[24,56,\"nations: 5, online_n: 7\"],[62,111,\"disability: 3, year_started: 32\"],[31,46,\"management: 2, year_started: 32\"],[4,56,\"nations: 5, online_teaching: 2\"],[31,52,\"year_started: 32, online_teaching: 2\"],[31,118,\"year_started: 32, website: 2\"],[18,111,\"gender: 4, online_n: 7\"],[4,118,\"nations: 5, website: 2\"],[6,52,\"management: 2, online_n: 7\"],[1,52,\"management: 2, online_teaching: 2\"],[9,118,\"age: 10, website: 2\"],[6,341,\"supervise_emp: 2, online_n: 7\"],[3,111,\"gender: 4, online_teaching: 2\"],[3,113,\"formal_education: 4, technology: 2\"],[1,341,\"supervise_emp: 2, online_teaching: 2\"],[1,118,\"management: 2, website: 2\"],[1,370,\"supervise_emp: 2, website: 2\"]],\"hovertemplate\":\"Test=%{x}\\u003cbr\\u003eChi-Squared Statistic=%{marker.size}\\u003cbr\\u003eDegrees of Freedom=%{customdata[0]}\\u003cbr\\u003eNaNs Dropped=%{customdata[1]}\\u003cbr\\u003eUnique Cases=%{customdata[2]}\\u003cbr\\u003eP-Value=%{marker.color}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"legendgroup\":\"\",\"marker\":{\"color\":{\"dtype\":\"f8\",\"bdata\":\"RbEad9em\\u002fDp0mtbqM4ycP6XmynwX1gM\\u002fwoL+bVwjQD\\u002fQid4yfBR3P+0MYFRuh0Y+tl+iCADxpD\\u002fMFhz3yf4OP1CRmch\\u002fW0M9dx\\u002fvvGLhVT\\u002fUsyQ2bp2gP6BnE9Ncn4E\\u002feLISvUQY4D7ivScvanRNP9ZmIs8wqeA+YxuOaJ6joD+vWbX3zySMP9JUiE53oWU\\u002fofx0xLlmdj\\u002fJ37qA3otBPzZ2Eco2hnI\\u002f6FLuZzk2kj8=\"},\"coloraxis\":\"coloraxis\",\"size\":{\"dtype\":\"f8\",\"bdata\":\"DVauyrJedkBgcC4uKRRsQL1hmwazn2NA1n4vUdQSYkA+Ruw3KIBaQDrgA1KiL1VAYtlR9EWqVECedaaxTrZRQMz5T9GeklBAVkUNmgcFTkAEgt6qJIVHQEAsAWVhqUFAbI3DyhYKPUDTqQNnSLY2QNPBp89\\u002f8zNAA+RRNzg9MkAswG8ZkQAwQPILbpVYaCxARmpSdZNKKUAmwJZRzfknQMQGIdBKHyBAt\\u002fJM\\u002fgR4FkA=\"},\"sizemode\":\"area\",\"sizeref\":0.8947966258072866,\"symbol\":\"circle\"},\"mode\":\"markers\",\"name\":\"\",\"orientation\":\"v\",\"showlegend\":false,\"x\":[\"Nations vs Year_started\",\"Year_started vs Online_n\",\"Gender vs Year_started\",\"Formal_education vs Year_started\",\"Social_class vs Year_started\",\"Nations vs Online_n\",\"Disability vs Year_started\",\"Management vs Year_started\",\"Nations vs Online_teaching\",\"Year_started vs Online_teaching\",\"Year_started vs Website\",\"Gender vs Online_n\",\"Nations vs Website\",\"Management vs Online_n\",\"Management vs Online_teaching\",\"Age vs Website\",\"Supervise_emp vs Online_n\",\"Gender vs Online_teaching\",\"Formal_education vs Technology\",\"Supervise_emp vs Online_teaching\",\"Management vs Website\",\"Supervise_emp vs Website\"],\"xaxis\":\"x\",\"y\":{\"dtype\":\"f8\",\"bdata\":\"DVauyrJedkBgcC4uKRRsQL1hmwazn2NA1n4vUdQSYkA+Ruw3KIBaQDrgA1KiL1VAYtlR9EWqVECedaaxTrZRQMz5T9GeklBAVkUNmgcFTkAEgt6qJIVHQEAsAWVhqUFAbI3DyhYKPUDTqQNnSLY2QNPBp89\\u002f8zNAA+RRNzg9MkAswG8ZkQAwQPILbpVYaCxARmpSdZNKKUAmwJZRzfknQMQGIdBKHyBAt\\u002fJM\\u002fgR4FkA=\"},\"yaxis\":\"y\",\"type\":\"scatter\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"xaxis\":{\"anchor\":\"y\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Test\"},\"categoryorder\":\"array\",\"categoryarray\":[\"Nations vs Year_started\",\"Year_started vs Online_n\",\"Gender vs Year_started\",\"Formal_education vs Year_started\",\"Social_class vs Year_started\",\"Nations vs Online_n\",\"Disability vs Year_started\",\"Management vs Year_started\",\"Nations vs Online_teaching\",\"Year_started vs Online_teaching\",\"Year_started vs Website\",\"Gender vs Online_n\",\"Nations vs Website\",\"Management vs Online_n\",\"Management vs Online_teaching\",\"Age vs Website\",\"Supervise_emp vs Online_n\",\"Gender vs Online_teaching\",\"Formal_education vs Technology\",\"Supervise_emp vs Online_teaching\",\"Management vs Website\",\"Supervise_emp vs Website\"]},\"yaxis\":{\"anchor\":\"x\",\"domain\":[0.0,1.0],\"title\":{\"text\":\"Chi-Squared Statistic\"}},\"coloraxis\":{\"colorbar\":{\"title\":{\"text\":\"P-Value\"}},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]},\"legend\":{\"tracegroupgap\":0,\"itemsizing\":\"constant\"},\"title\":{\"text\":\"Chi-Squared Test Results: Tests vs Chi-Squared Statistic\"}},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('24be2fd1-05a4-49d2-950d-d737a4fcd497');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n:::\n:::\n\n\n::: {#0a023708 .cell execution_count=7}\n``` {.python .cell-code}\nimport pandas as pd\nfrom scipy.stats import chi2_contingency\nimport itertools\nimport plotly.graph_objects as go\n\n# Load the survey dataframe\nsurvey_social_class_merged = pd.read_pickle('data/survey_social_class_merged.pkl')\n\n# Define independent and dependent variables\nindependent_vars = ['age', 'gender', 'nations', 'ethnicity', 'sexuality', 'disability', \n                    'employment_other_type', 'formal_education', 'management', 'supervise_emp', 'social_class']\ndependent_vars = ['technology', 'website', 'online_teaching', 'online_n']\nyear_started = ['year_started']  # can act as both IV and DV\n\n# Function to perform chi-squared tests and return Plotly table for significant results\ndef perform_chi_squared_tests(data):\n    significant_results = []  # List to hold the significant results\n\n    # Create all unique pairs of IVs and DVs, including year_started as both\n    for var1, var2 in itertools.product(independent_vars + year_started, dependent_vars + year_started):\n        if var1 != var2:\n            # Drop NaN values separately for the variables being tested\n            data_cleaned = data.dropna(subset=[var1, var2])\n\n            # Count unique cases for each variable\n            cases_var1 = data_cleaned[var1].nunique()\n            cases_var2 = data_cleaned[var2].nunique()\n\n            # Conduct chi-squared test\n            table = pd.crosstab(data_cleaned[var1], data_cleaned[var2])\n            chi2_stat, p_val, dof, _ = chi2_contingency(table)\n\n            # Check if the relationship is significant (using a threshold, e.g., 0.05)\n            if p_val < 0.05:\n                # Append results to the list\n                result = [f\"{var1.capitalize()} vs {var2.capitalize()}\",\n                          round(chi2_stat, 2), dof, p_val, data[var1].isna().sum() + data[var2].isna().sum(),\n                          f\"{var1}: {cases_var1}, {var2}: {cases_var2}\"]\n                significant_results.append(result)\n\n    # Sort the results by Chi-Squared statistic in descending order\n    significant_results.sort(key=lambda x: x[1], reverse=True)\n\n    # Create a Plotly table\n    fig = go.Figure(data=[go.Table(\n        header=dict(values=[\"Test\", \"Chi-Squared Statistic\", \"Degrees of Freedom\", \"P-Value\", \"NaNs Dropped\", \"Unique Cases\"]),\n        cells=dict(values=list(zip(*significant_results)))\n    )])\n    fig.update_layout(title=\"Significant Results of Chi-Squared Tests (Sorted by Chi-Squared Statistic)\")\n    return fig\n\n# Perform chi-squared tests\nsignificant_results_fig = perform_chi_squared_tests(survey_social_class_merged)\n\n# Show the table\nsignificant_results_fig.show()\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.4.0.min.js\" integrity=\"sha256-KEmPoupLpFyGMyGAiOsiNDbKDKAvxXAn/W+oQa0ZAfk=\" crossorigin=\"anonymous\"></script>                <div id=\"c23bcba8-f87d-404e-8817-e0466ee7e1c4\" class=\"plotly-graph-div\" style=\"height:525px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"c23bcba8-f87d-404e-8817-e0466ee7e1c4\")) {                    Plotly.newPlot(                        \"c23bcba8-f87d-404e-8817-e0466ee7e1c4\",                        [{\"cells\":{\"values\":[[\"Nations vs Year_started\",\"Year_started vs Online_n\",\"Gender vs Year_started\",\"Formal_education vs Year_started\",\"Social_class vs Year_started\",\"Nations vs Online_n\",\"Disability vs Year_started\",\"Management vs Year_started\",\"Nations vs Online_teaching\",\"Year_started vs Online_teaching\",\"Year_started vs Website\",\"Gender vs Online_n\",\"Nations vs Website\",\"Management vs Online_n\",\"Management vs Online_teaching\",\"Age vs Website\",\"Supervise_emp vs Online_n\",\"Gender vs Online_teaching\",\"Formal_education vs Technology\",\"Supervise_emp vs Online_teaching\",\"Management vs Website\",\"Supervise_emp vs Website\"],[357.92,224.63,156.99,144.59,106.0,84.74,82.66,70.85,66.29,60.04,47.04,35.32,29.04,22.71,19.95,18.24,16.0,14.2,12.65,11.99,8.06,5.62],[124,186,93,93,72,24,62,31,4,31,31,18,4,6,1,9,6,3,3,1,1,1],[1.4812594771090533e-24,0.02787858124579619,3.7834731846553706e-05,0.0004924966160509624,0.005634770537570735,1.0490895829140457e-08,0.04090118508719291,5.911878441903842e-05,1.3754273150038289e-13,0.0013354744184983205,0.03245109949998662,0.0086047412791464,7.67459815372819e-06,0.0008988874890842292,7.944536694548721e-06,0.03249831224734725,0.013742089030228081,0.002640469571142925,0.005469060567803969,0.0005354725303368053,0.004522527714554017,0.017784974068109444],[102,98,157,158,384,108,157,69,108,98,164,163,174,75,75,229,393,163,176,393,141,459],[\"nations: 5, year_started: 32\",\"year_started: 32, online_n: 7\",\"gender: 4, year_started: 32\",\"formal_education: 4, year_started: 32\",\"social_class: 4, year_started: 25\",\"nations: 5, online_n: 7\",\"disability: 3, year_started: 32\",\"management: 2, year_started: 32\",\"nations: 5, online_teaching: 2\",\"year_started: 32, online_teaching: 2\",\"year_started: 32, website: 2\",\"gender: 4, online_n: 7\",\"nations: 5, website: 2\",\"management: 2, online_n: 7\",\"management: 2, online_teaching: 2\",\"age: 10, website: 2\",\"supervise_emp: 2, online_n: 7\",\"gender: 4, online_teaching: 2\",\"formal_education: 4, technology: 2\",\"supervise_emp: 2, online_teaching: 2\",\"management: 2, website: 2\",\"supervise_emp: 2, website: 2\"]]},\"header\":{\"values\":[\"Test\",\"Chi-Squared Statistic\",\"Degrees of Freedom\",\"P-Value\",\"NaNs Dropped\",\"Unique Cases\"]},\"type\":\"table\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermap\":[{\"type\":\"scattermap\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"title\":{\"text\":\"Significant Results of Chi-Squared Tests (Sorted by Chi-Squared Statistic)\"}},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('c23bcba8-f87d-404e-8817-e0466ee7e1c4');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n:::\n:::\n\n\n::: {#7cced468 .cell execution_count=8}\n``` {.python .cell-code}\n# Load the survey dataframe\nsurvey_social_class_merged = pd.read_pickle('data/survey_social_class_merged.pkl')\n\n# Define independent and dependent variables\nindependent_vars = ['age', 'gender', 'nations', 'ethnicity', 'sexuality', 'disability', \n                    'employment_other_type', 'formal_education', 'management', 'supervise_emp', 'social_class']\ndependent_vars = ['technology', 'website', 'online_teaching', 'online_n']\nyear_started = ['year_started']  # can act as both IV and DV\n\n# Function to perform chi-squared tests and return PrettyTables for significant results\ndef perform_chi_squared_tests(data):\n    significant_results = []  # List to hold the significant results\n\n    # Create all unique pairs of IVs and DVs, including year_started as both\n    for var1, var2 in itertools.product(independent_vars + year_started, dependent_vars + year_started):\n        if var1 != var2:\n            # Drop NaN values separately for the variables being tested\n            data_cleaned = data.dropna(subset=[var1, var2])\n\n            # Count unique cases for each variable\n            cases_var1 = data_cleaned[var1].nunique()\n            cases_var2 = data_cleaned[var2].nunique()\n\n            # Conduct chi-squared test\n            table = pd.crosstab(data_cleaned[var1], data_cleaned[var2])\n            chi2_stat, p_val, dof, _ = chi2_contingency(table)\n\n            # Check if the relationship is significant (using a threshold, e.g., 0.05)\n            if p_val < 0.05:\n                # Append results to the list\n                result = [f\"{var1.capitalize()} vs {var2.capitalize()}\",\n                          round(chi2_stat, 2), dof, p_val, data[var1].isna().sum() + data[var2].isna().sum(),\n                          f\"{var1}: {cases_var1}, {var2}: {cases_var2}\"]\n                significant_results.append(result)\n\n    # Sort the results by Chi-Squared statistic in descending order\n    significant_results.sort(key=lambda x: x[1], reverse=True)\n\n    # Create PrettyTable\n    significant_results_pt = PrettyTable()\n    significant_results_pt.field_names = [\"Test\", \"Chi-Squared Statistic\", \"Degrees of Freedom\", \"P-Value\", \"NaNs Dropped\", \"Unique Cases\"]\n\n    # Add sorted results to PrettyTable\n    for result in significant_results:\n        significant_results_pt.add_row(result)\n\n    return significant_results_pt\n\n# Perform chi-squared tests\nsignificant_results_table = perform_chi_squared_tests(survey_social_class_merged)\n\n# Print the tables\nprint(\"Significant Results of Chi-Squared Tests (Sorted by Chi-Squared Statistic)\")\nprint(significant_results_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSignificant Results of Chi-Squared Tests (Sorted by Chi-Squared Statistic)\n+----------------------------------+-----------------------+--------------------+------------------------+--------------+---------------------------------------+\n|               Test               | Chi-Squared Statistic | Degrees of Freedom |        P-Value         | NaNs Dropped |              Unique Cases             |\n+----------------------------------+-----------------------+--------------------+------------------------+--------------+---------------------------------------+\n|     Nations vs Year_started      |         357.92        |        124         | 1.4812594771090533e-24 |     102      |      nations: 5, year_started: 32     |\n|     Year_started vs Online_n     |         224.63        |        186         |  0.02787858124579619   |      98      |     year_started: 32, online_n: 7     |\n|      Gender vs Year_started      |         156.99        |         93         | 3.7834731846553706e-05 |     157      |      gender: 4, year_started: 32      |\n| Formal_education vs Year_started |         144.59        |         93         | 0.0004924966160509624  |     158      | formal_education: 4, year_started: 32 |\n|   Social_class vs Year_started   |         106.0         |         72         |  0.005634770537570735  |     384      |   social_class: 4, year_started: 25   |\n|       Nations vs Online_n        |         84.74         |         24         | 1.0490895829140457e-08 |     108      |        nations: 5, online_n: 7        |\n|    Disability vs Year_started    |         82.66         |         62         |  0.04090118508719291   |     157      |    disability: 3, year_started: 32    |\n|    Management vs Year_started    |         70.85         |         31         | 5.911878441903842e-05  |      69      |    management: 2, year_started: 32    |\n|    Nations vs Online_teaching    |         66.29         |         4          | 1.3754273150038289e-13 |     108      |     nations: 5, online_teaching: 2    |\n| Year_started vs Online_teaching  |         60.04         |         31         | 0.0013354744184983205  |      98      |  year_started: 32, online_teaching: 2 |\n|     Year_started vs Website      |         47.04         |         31         |  0.03245109949998662   |     164      |      year_started: 32, website: 2     |\n|        Gender vs Online_n        |         35.32         |         18         |   0.0086047412791464   |     163      |         gender: 4, online_n: 7        |\n|        Nations vs Website        |         29.04         |         4          |  7.67459815372819e-06  |     174      |         nations: 5, website: 2        |\n|      Management vs Online_n      |         22.71         |         6          | 0.0008988874890842292  |      75      |       management: 2, online_n: 7      |\n|  Management vs Online_teaching   |         19.95         |         1          | 7.944536694548721e-06  |      75      |   management: 2, online_teaching: 2   |\n|          Age vs Website          |         18.24         |         9          |  0.03249831224734725   |     229      |          age: 10, website: 2          |\n|    Supervise_emp vs Online_n     |          16.0         |         6          |  0.013742089030228081  |     393      |     supervise_emp: 2, online_n: 7     |\n|    Gender vs Online_teaching     |          14.2         |         3          |  0.002640469571142925  |     163      |     gender: 4, online_teaching: 2     |\n|  Formal_education vs Technology  |         12.65         |         3          |  0.005469060567803969  |     176      |   formal_education: 4, technology: 2  |\n| Supervise_emp vs Online_teaching |         11.99         |         1          | 0.0005354725303368053  |     393      |  supervise_emp: 2, online_teaching: 2 |\n|      Management vs Website       |          8.06         |         1          |  0.004522527714554017  |     141      |       management: 2, website: 2       |\n|     Supervise_emp vs Website     |          5.62         |         1          |  0.017784974068109444  |     459      |      supervise_emp: 2, website: 2     |\n+----------------------------------+-----------------------+--------------------+------------------------+--------------+---------------------------------------+\n```\n:::\n:::\n\n\n# Which factors most influence mindfulness teaching?\n\n## Summary of Logistic Regression Analysis\n\n### Overall Interpretation\n- **Formal Education as a Stronger Predictor**: Formal education level is a more significant predictor of technology use in mindfulness teaching than age.\n- **Moderate Accuracy**: The model has an accuracy of approximately 61.67%, indicating moderate predictive power.\n- **Balanced Predictions**: The model shows balanced precision, recall, and F1-scores for both classes (technology use and non-use).\n\nThe data was loaded and preprocessed, age and formal education were encoded, and SMOTE was used to balance the dataset. A logistic regression model was built and trained. The model coefficients were calculated to indicate the influence of age and formal education on use of technology. The coefficients show for age (`0.0592`) and formal education (`0.7411`) suggest formal education is a stronger influence than age on use of technology.\n\n- Formal education level is a more significant predictor of technology use in mindfulness teaching than age.\n\nHowever, the ROC AUC - which assesses the model's ability to distinguish between classes (in this case, age and formal education), was approximately `0.604`, indicating limited discrimination ability between classes.\n\nThe confusion matrix and classification report provides detailed insights into model performance, reflecting a balance between precision and recall for predicting both technology use and non-use.\n\nOverall, this analysis suggests the need for further model refinement and consideration of additional variables to enhance predictive accuracy.\n\n::: {#02e19b30 .cell execution_count=9}\n``` {.python .cell-code}\n# Load the survey dataframe\nsurvey_clean = pd.read_pickle('data/tidied_survey.pkl')\n\n# Only age/formal_education as category here; map `technology` to 0/1 after dropna\n# (assigning int 0/1 into a categorical `technology` column fails on newer pandas)\ncategory_columns = ['age', 'technology', 'formal_education']\nfor col in ['age', 'formal_education']:\n    survey_clean[col] = survey_clean[col].astype('category')\n\n# Drop rows with NaN values in the relevant columns\nsurvey_clean = survey_clean.dropna(subset=category_columns).copy()\n\n# Convert 'technology' from Yes/No to 0/1\nsurvey_clean['technology'] = survey_clean['technology'].map({'Yes': 1, 'No': 0}).astype('int64')\n\n# Encoding 'age' and 'formal_education'\nage_mapping = {'25-29': 1, '30-34': 2, '35-39': 3, '40-44': 4, '45-49': 5,\n               '50-54': 6, '55-59': 7, '60-64': 8, '65+': 9, 'Prefer not to say': 10}\neducation_mapping = {'Non-degree': 1, 'Degree': 2, 'Higher degree': 3, 'Prefer not to say': 4}\nsurvey_clean.loc[:, 'age_encoded'] = survey_clean['age'].map(age_mapping)\nsurvey_clean.loc[:, 'formal_education_encoded'] = survey_clean['formal_education'].map(education_mapping)\n\n# Ensure no NaN values remain\nsurvey_clean = survey_clean.dropna(subset=['age_encoded', 'formal_education_encoded'])\n\n# Define predictor variables and outcome variable\nX = survey_clean[['age_encoded', 'formal_education_encoded']]\ny = survey_clean['technology']\n\n# Addressing Imbalance using SMOTE\nsm = SMOTE(random_state=42)\nX_res, y_res = sm.fit_resample(X, y)\n\n# Split dataset into training and testing sets\nX_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.3, random_state=0)\n\n# Build logistic regression model\nlogreg = LogisticRegression()\nlogreg.fit(X_train, y_train)\n\n# Predict test set results and calculate accuracy\ny_pred = logreg.predict(X_test)\n\n# Model Coefficients\nprint(\"\\nModel Coefficients:\")\nfor col, coef in zip(X.columns, logreg.coef_[0]):\n    print(f\"{col}: {coef}\")\n\n# Evaluation Metrics\naccuracy = logreg.score(X_test, y_test)\nroc_auc = roc_auc_score(y_test, logreg.predict_proba(X_test)[:, 1])\nconf_matrix = confusion_matrix(y_test, y_pred)\nclass_report = classification_report(y_test, y_pred, zero_division=0)\n\nprint('\\nAccuracy of logistic regression classifier on test set:', accuracy)\nprint('\\nROC AUC Score:', roc_auc)\nprint('\\nConfusion Matrix:\\n', conf_matrix)\nprint('\\nClassification Report:\\n', class_report)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nModel Coefficients:\nage_encoded: 0.05916298277924698\nformal_education_encoded: 0.741145842777389\n\nAccuracy of logistic regression classifier on test set: 0.6166666666666667\n\nROC AUC Score: 0.6036770163285502\n\nConfusion Matrix:\n [[104  84]\n [ 54 118]]\n\nClassification Report:\n               precision    recall  f1-score   support\n\n           0       0.66      0.55      0.60       188\n           1       0.58      0.69      0.63       172\n\n    accuracy                           0.62       360\n   macro avg       0.62      0.62      0.62       360\nweighted avg       0.62      0.62      0.62       360\n\n```\n:::\n:::\n\n\n# Factors Influencing Use of a Professional Website\n\nWe conducted in-depth analysis of the factors influencing the use of a professional website. The model considers various predictors:\n\n- `age`: The age of the teachers.\n- `nations`: The nations in which they teach.\n- `management`: Whether they hold a management position.\n- `year_started`: The year when they started teaching.\n\nThe dataset was preprocessed by dropping rows with missing values and by encoding categorical variables. `management` and `website` were converted from Yes/No to binary (0/1), `age` was mapped to numerical categories based on ranges, `nations` was encoded as a numeric variable, and `year_started` was converted to an integer type.\n\nThe dataset was split into training and test sets (70-30 split). A logistic regression model was trained on the processed data, due to the outcome variable being categorical. \n\n## Results\n\nThe model shows that having a management role is a significant positive predictor for using a professional website, while `age` and `nations` where mindfulness is taught show a negative correlation. However, the overall accuracy and ROC AUC score suggest that the model has moderate predictive power, and there is substantial room for improvement.\n\n### Website Variable Distribution\n- Having a Website (`1`): 392\n- Not Having a Website (`0`): 258\n\n### Model Coefficients\n\nThe model coefficients suggest the following positive correlations:\n\n- Management role is positively correlated with having a professional website (`0.6109`)\n- Very slight positive impact on the likelihood of having a website the later year started teaching (`0.00041`)\n\nThe model coefficients suggest the following negative correlations:\n\n- Negative correlation between nations where mindfulness is taught and having a professional website (`-0.1856`)\n- Slight decrease in likelihood of having a professional website with increasing age (`-0.06271`)\n\n### Model Performance\n- **Accuracy**: 60.51% on the test set.\n- **ROC AUC Score**: 0.5509, indicating moderate discriminative ability.\n\n### Classification Report\n- **Precision** for not having a website (`0`): 46%\n- **Recall** for not having a website (`0`): 17%\n- **F1-Score** for not having a website (`0`): 25%\n- **Precision** for having a website (`1`): 63%\n- **Recall** for having a website (`1`): 88%\n- **F1-Score** for having a website (`1`): 73%\n\n::: {#ffab6140 .cell execution_count=10}\n``` {.python .cell-code}\n# Load the survey dataframe\nsurvey_clean = pd.read_pickle('data/tidied_survey.pkl')\n\n# Drop NA values from variables of interest\nsurvey_clean = survey_clean.dropna(subset=['age', 'management', 'website', 'year_started', 'nations'])\n\n# Print initial data types\nprint(\"Initial Data Types:\\n\", survey_clean[['age', 'management', 'website', 'year_started', 'nations']].dtypes)\n\n# Convert 'management' and 'website' from Yes/No to 0/1\nsurvey_clean['management'] = survey_clean['management'].map({'Yes': 1, 'No': 0})\nsurvey_clean['website'] = survey_clean['website'].map({'Yes': 1, 'No': 0})\n\n# Convert 'year_started' to integer\nsurvey_clean['year_started'] = survey_clean['year_started'].astype(int)\n\n# Encoding 'age' using the provided mapping\nage_mapping = {'25-29': 1, '30-34': 2, '35-39': 3, '40-44': 4, '45-49': 5,\n               '50-54': 6, '55-59': 7, '60-64': 8, '65+': 9, 'Prefer not to say': 10}\nsurvey_clean['age'] = survey_clean['age'].map(age_mapping)\n\n# Encoding 'nations' as numeric\nprint(\"Unique levels in 'nations':\\n\", survey_clean['nations'].unique())\nlabel_encoder = LabelEncoder()\nsurvey_clean['nations'] = label_encoder.fit_transform(survey_clean['nations'])\n\n# Print updated data types\nprint(\"Updated Data Types:\\n\", survey_clean[['age', 'management', 'website', 'year_started', 'nations']].dtypes)\n\n# Select only the relevant columns for the model\nX = survey_clean[['age', 'management', 'year_started', 'nations']]\ny = survey_clean['website']\n\n# Check balance of the 'website' variable\nwebsite_counts = y.value_counts()\nprint(\"Website Variable Distribution:\\n\", website_counts)\n\n# Proceed without SMOTE as the dataset is balanced\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)\n\n# Build logistic regression model\nlogreg = LogisticRegression()\nlogreg.fit(X_train, y_train)\n\n# Predict test set results and calculate accuracy\ny_pred = logreg.predict(X_test)\n\n# Model Coefficients\nprint(\"\\nModel Coefficients:\")\nfor col, coef in zip(X_train.columns, logreg.coef_[0]):\n    print(f\"{col}: {coef}\")\n\n# Evaluation Metrics\naccuracy = logreg.score(X_test, y_test)\nroc_auc = roc_auc_score(y_test, logreg.predict_proba(X_test)[:, 1])\nconf_matrix = confusion_matrix(y_test, y_pred)\nclass_report = classification_report(y_test, y_pred, zero_division=0)\n\nprint('\\nAccuracy of logistic regression classifier on test set:', accuracy)\nprint('\\nROC AUC Score:', roc_auc)\nprint('\\nConfusion Matrix:\\n', conf_matrix)\nprint('\\nClassification Report:\\n', class_report)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nInitial Data Types:\n age             category\nmanagement      category\nwebsite         category\nyear_started       Int64\nnations         category\ndtype: object\nUnique levels in 'nations':\n ['England', 'Scotland', 'Wales', 'Mixed', 'Northern Ireland']\nCategories (5, str): ['England', 'Mixed', 'Northern Ireland', 'Scotland', 'Wales']\nUpdated Data Types:\n age             category\nmanagement      category\nwebsite         category\nyear_started       int64\nnations            int64\ndtype: object\nWebsite Variable Distribution:\n website\n1    392\n0    258\nName: count, dtype: int64\n\nModel Coefficients:\nage: -0.0606120990965871\nmanagement: 0.7208782154253373\nyear_started: -0.0127682764668585\nnations: -0.2918685914557494\n\nAccuracy of logistic regression classifier on test set: 0.6256410256410256\n\nROC AUC Score: 0.5711666666666667\n\nConfusion Matrix:\n [[ 17  58]\n [ 15 105]]\n\nClassification Report:\n               precision    recall  f1-score   support\n\n           0       0.53      0.23      0.32        75\n           1       0.64      0.88      0.74       120\n\n    accuracy                           0.63       195\n   macro avg       0.59      0.55      0.53       195\nweighted avg       0.60      0.63      0.58       195\n\n```\n:::\n:::\n\n\n# Nations and Use of Technology\n\nWe explored in greater depth the relation between the nations where mindfulness is taught and the use of technology.\n\nWe tested whether there is a relationship between the country (or nation) where people are teaching mindfulness and the following behaviors or conditions:\n\n- Whether they use technology or not.\n- Whether they teach online.\n- The number of students they teach online.\n\nWe conducted Chi-Squared tests and Logistic Regression analyses to test for significant relationships.\n\nWe found:\n\n- **No significant relationship between the nation where mindfulness is taught and whether the teacher uses technology**: This means that the likelihood of someone using technology is roughly the same, regardless of which country the teach mindfulness in. All nations, except Scotland, tend to use technology less than England. However, none of these differences are statistically significant, meaning we can’t confidently say these differences aren’t due to random chance.\n\n- **Significant relationship between the nation where mindfulness is taught and whether the teacher teaches online:** depending on the country where mindfulness is taught, teachers are more likely to teach online than in others.\n\n- **Significant relationship between the country where mindfulness is taught and the number of students they teach online**: some mindfulness teachers might be teaching more students online compared to those from other countries.\n\n::: {#9b2b7b87 .cell execution_count=11}\n``` {.python .cell-code}\n# Load the survey dataframe\nsurvey_clean = pd.read_pickle('data/tidied_survey.pkl')\n\n# Chi-squared tests\ncontingency_tables = {\n    'technology': pd.crosstab(survey_clean['nations'], survey_clean['technology']),\n    'online_teaching': pd.crosstab(survey_clean['nations'], survey_clean['online_teaching']),\n    'online_n': pd.crosstab(survey_clean['nations'], survey_clean['online_n']),\n    'website': pd.crosstab(survey_clean['nations'], survey_clean['website'])\n}\n\n# Display chi-squared test results and contingency tables\nresults_pt = PrettyTable([\"Test\", \"Chi-Squared Statistic\", \"Degrees of Freedom\", \"P-Value\"])\nfor test, table in contingency_tables.items():\n    chi2_stat, p_val, dof, _ = chi2_contingency(table)\n    results_pt.add_row([f\"Nations vs {test.capitalize()}\", chi2_stat, dof, p_val])\n    table_pt = PrettyTable(['Nation'] + list(table.columns))\n    for row in table.itertuples():\n        table_pt.add_row([row.Index] + list(row[1:]))\n    print(f\"Contingency Table for {test.capitalize()}\\n{table_pt}\\n\")\nprint(f\"Results of Chi-Squared Tests\\n{results_pt}\\n\")\n\n# Logistic Regression for 'website'\nimport statsmodels.api as sm\nlogistic_model = smf.glm(formula='website ~ nations', family=sm.families.Binomial(), data=survey_clean).fit()\ncoef_summary = logistic_model.summary2().tables[1]\nodds_ratios = coef_summary['Coef.'].apply(np.exp)\nlower_95 = coef_summary['[0.025'].apply(np.exp)\nupper_95 = coef_summary['0.975]'].apply(np.exp)\nresults_table = PrettyTable(['Variable', 'Odds Ratio', '95% CI Lower', '95% CI Upper'])\nfor variable, odds_ratio, ci_lower, ci_upper in zip(coef_summary.index, odds_ratios, lower_95, upper_95):\n    results_table.add_row([variable, odds_ratio, ci_lower, ci_upper])\nprint(f\"Logistic Regression Results\\n{results_table}\\n\")\n\n# Plotting Odds Ratios\nplot_data = pd.DataFrame({\n    'Variable': coef_summary.index,\n    'Odds Ratio': odds_ratios,\n    '95% CI Lower': lower_95,\n    '95% CI Upper': upper_95\n})\n\nsns.pointplot(x='Odds Ratio', y='Variable', data=plot_data, join=False, capsize=0.1, linestyle='none')\nplt.axvline(x=1, linestyle='--')\nplt.xlabel('Odds Ratio with 95% CI')\nplt.ylabel('Variable')\nplt.title('Odds of Website Usage by Nation')\nplt.show()\n\n# Participants count from each nation\nnation_counts = survey_clean['nations'].value_counts()\nnation_counts_table = PrettyTable([\"Nation\", \"Count\"])\nfor nation, count in nation_counts.items():\n    nation_counts_table.add_row([nation, count])\nprint(f\"Number of Participants from Each Nation\\n{nation_counts_table}\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nContingency Table for Technology\n+------------------+----+-----+\n|      Nation      | No | Yes |\n+------------------+----+-----+\n|     England      | 43 | 446 |\n|      Mixed       | 6  |  97 |\n| Northern Ireland | 0  |  2  |\n|     Scotland     | 9  |  74 |\n|      Wales       | 2  |  25 |\n+------------------+----+-----+\n\nContingency Table for Online_teaching\n+------------------+-----+-----+\n|      Nation      |  No | Yes |\n+------------------+-----+-----+\n|     England      | 385 | 108 |\n|      Mixed       |  46 |  59 |\n| Northern Ireland |  2  |  0  |\n|     Scotland     |  75 |  10 |\n|      Wales       |  23 |  4  |\n+------------------+-----+-----+\n\nContingency Table for Online_n\n+------------------+-----+-----+-------+-------+--------+------+---------------+\n|      Nation      |  0  | 1-5 | 11-20 | 21-50 | 51-100 | 6-10 | More than 100 |\n+------------------+-----+-----+-------+-------+--------+------+---------------+\n|     England      | 332 |  50 |   17  |   23  |   23   |  24  |       24      |\n|      Mixed       |  37 |  9  |   8   |   12  |   6    |  8   |       25      |\n| Northern Ireland |  2  |  0  |   0   |   0   |   0    |  0   |       0       |\n|     Scotland     |  66 |  6  |   2   |   0   |   3    |  2   |       6       |\n|      Wales       |  17 |  2  |   0   |   1   |   0    |  1   |       6       |\n+------------------+-----+-----+-------+-------+--------+------+---------------+\n\nContingency Table for Website\n+------------------+-----+-----+\n|      Nation      |  No | Yes |\n+------------------+-----+-----+\n|     England      | 181 | 269 |\n|      Mixed       |  19 |  76 |\n| Northern Ireland |  0  |  2  |\n|     Scotland     |  42 |  35 |\n|      Wales       |  16 |  10 |\n+------------------+-----+-----+\n\nResults of Chi-Squared Tests\n+----------------------------+-----------------------+--------------------+------------------------+\n|            Test            | Chi-Squared Statistic | Degrees of Freedom |        P-Value         |\n+----------------------------+-----------------------+--------------------+------------------------+\n|   Nations vs Technology    |   1.810025240238794   |         4          |   0.7706476707611541   |\n| Nations vs Online_teaching |   66.29094345865377   |         4          | 1.3754273150038289e-13 |\n|    Nations vs Online_n     |   84.74428224924569   |         24         | 1.0490895829140457e-08 |\n|     Nations vs Website     |   29.039410279028218  |         4          |  7.67459815372819e-06  |\n+----------------------------+-----------------------+--------------------+------------------------+\n\nLogistic Regression Results\n+-----------------------------+------------------------+--------------------+--------------------+\n|           Variable          |       Odds Ratio       |    95% CI Lower    |    95% CI Upper    |\n+-----------------------------+------------------------+--------------------+--------------------+\n|          Intercept          |   0.6728624535315983   | 0.5573067233250392 | 0.8123782872587159 |\n|       nations[T.Mixed]      |  0.37154696132596815   | 0.2171966609781953 | 0.6355859424764325 |\n| nations[T.Northern Ireland] | 1.7391763923916894e-09 |        0.0         |        inf         |\n|     nations[T.Scotland]     |   1.7834254143646349   | 1.0963579154034913 | 2.9010655771396654 |\n|       nations[T.Wales]      |   2.377900552486186    | 1.0554566240889736 | 5.357312568287457  |\n+-----------------------------+------------------------+--------------------+--------------------+\n\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](mapmind_technology_files/figure-html/cell-12-output-2.png){width=724 height=447}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber of Participants from Each Nation\n+------------------+-------+\n|      Nation      | Count |\n+------------------+-------+\n|     England      |  493  |\n|      Mixed       |  105  |\n|     Scotland     |   85  |\n|      Wales       |   27  |\n| Northern Ireland |   2   |\n+------------------+-------+\n\n```\n:::\n:::\n\n\n## Nation where mindfulness is taught influences uses of professional website\n\nWe tested for differences in use of a professional website by nation (country).\n\nWe found:\n\n- **Wales and Scotland show a moderate increase in website usage compared to England, and these increases are statistically significant**: This means that the observed higher website usage in Wales and Scotland is not just due to random chance, but likely reflects a real trend.\n\n- **A strong decrease in website usage in the “Mixed” group compared to England, and this decrease is highly significant**: This suggests a robust trend of lesser website usage in this group relative to England.\n\n- **A decrease in website usage in Northern Ireland compared to England, but the strength of this decrease is “very low”, and it’s not statistically significant**: we can’t be confident that this observed decrease isn’t just due to random chance.\n\nIn summary, we found that **mindfulness teachers who teach in both Wales and Scotland are using professional websites more than those teaching in England, with those teaching in Wales leading slightly.**\n\n- Those teaching in Wales are `2.38` times more likely to use websites compared to those in England.\n- Those teaching in Scotland are `1.78` times more likely to use websites than those in England.\n- The odds ratio for Northern Ireland is “nearly 0”, indicating that there’s almost no chance for teachers from Northern Ireland to use a website compared to England. Participants teaching in Northern Ireland are hardly using websites at all, when compared to those teaching in England.\n- The “Mixed” group also tends to use websites less than those teaching in England, with an odds ratio of `0.37`.\n\nWe tested for differences in online teaching by nation (country).\n\nWe found:\n\n- **Mindfulness teachers teaching in Scotland seem to be doing more online teaching compared to England, while teachers who teach in a “Mix” of nations do significantly less.** The other nations don’t show significant differences from England in terms of online teaching.\n\n## Factors Predicting Online Teaching\n\nA logistic regression model was trained to predict whether mindfulness teachers engage in online teaching based on several features, including gender, years of teaching experience, whether they hold a management position, and their nationality.\n\nThe results show the following positive associations:\n\n- Holding a management position is positively associated with online teaching (`0.625`, positive coefficient)\n- Being male is positively associated with online teaching (`0.495`, positive coefficient)\n- Having an \"Other\" gender is positively associated with online teaching (`0.0341`, positive coefficient)\n- Preferring not to specify gender is positively associated with online teaching (`0.0113`, positive coefficient)\n\nThe results show the following negative associations:\n\n- The number of years a teacher has been teaching is negatively associated with online teaching (`-0.000033`, negative coefficient)\n- The nation where mindfulness is taught has a negative association with online teaching (`-0.258`, negative coefficient)\n\nThe logistic regression model achieved an accuracy of `67%` on the test set, indicating that it can predict online teaching behavior to some extent. However, it's important to note that there is room for improvement in terms of precision and recall, especially for class 1 (engaging in online teaching, `43%`). Further analysis and feature engineering may help improve the model's performance.\n\n### Model Performance:\n\n- Accuracy of the logistic regression classifier on the test set: 0.67 (67%)\n- ROC AUC Score: 0.628\n- Confusion Matrix:\n  - True Positives: 30\n  - False Positives: 39\n  - True Negatives: 102\n  - False Negatives: 27\n\n### Classification Report:\n\n- Precision for class 0 (not engaging in online teaching): 0.79\n- Recall for class 0: 0.72\n- F1-score for class 0: 0.76\n- Precision for class 1 (engaging in online teaching): 0.43\n- Recall for class 1: 0.53\n- F1-score for class 1: 0.48\n\n::: {#d0ae5ea5 .cell execution_count=12}\n``` {.python .cell-code}\n# Load the survey dataframe\nsurvey_clean = pd.read_pickle('data/tidied_survey.pkl')\n\n# Convert 'management' and 'online_teaching' from Yes/No to 0/1\nsurvey_clean['management'] = survey_clean['management'].map({'Yes': 1, 'No': 0})\nsurvey_clean['online_teaching'] = survey_clean['online_teaching'].map({'Yes': 1, 'No': 0})\n\n# Drop NA values only from the variables being tested\ncols_to_check = ['gender', 'management', 'online_teaching', 'year_started', 'nations']\nsurvey_clean = survey_clean.dropna(subset=cols_to_check)\n\n# One-hot encoding for 'gender'\ngender_encoder = OneHotEncoder(drop='first', sparse_output=False)\ngender_encoded = gender_encoder.fit_transform(survey_clean[['gender']])\ngender_encoded_df = pd.DataFrame(gender_encoded, columns=gender_encoder.get_feature_names_out(['gender']))\n\n# Join the encoded dataframe with the original dataframe\nsurvey_clean = survey_clean.reset_index(drop=True)  # Resetting index to ensure proper row alignment\nsurvey_clean = pd.concat([survey_clean, gender_encoded_df], axis=1)\n\n# Encoding 'nations' as numeric\nlabel_encoder = LabelEncoder()\nsurvey_clean['nations'] = label_encoder.fit_transform(survey_clean['nations'])\n\n# Convert 'year_started' to integer\nsurvey_clean['year_started'] = survey_clean['year_started'].astype(int)\n\n# Select only the relevant columns for the model\nfeature_cols = ['management', 'year_started', 'nations'] + list(gender_encoded_df.columns)\nX = survey_clean[feature_cols]\ny = survey_clean['online_teaching']\n\n# Splitting the dataset into training and test sets\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)\n\n# Applying SMOTE to the training set\n# SMOTE - Synthetic Minority Over-sampling Technique\n# https://imbalanced-learn.org/stable/references/generated/imblearn.over_sampling.SMOTE.html\nsmote = SMOTE(random_state=0)\nX_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)\n\n# Drop rows with NaN values from X_train_smote\nX_train_smote = X_train_smote.dropna()\ny_train_smote = y_train_smote.loc[X_train_smote.index]  # Update y_train_smote accordingly\n\n# Build logistic regression model\nlogreg = LogisticRegression()\nlogreg.fit(X_train_smote, y_train_smote)\n\n# Predict test set results and calculate accuracy\ny_pred = logreg.predict(X_test)\n\n# Model Coefficients\nprint(\"\\nModel Coefficients:\")\nfor col, coef in zip(X_train_smote.columns, logreg.coef_[0]):\n    print(f\"{col}: {coef}\")\n\n# Evaluation Metrics\naccuracy = logreg.score(X_test, y_test)\nroc_auc = roc_auc_score(y_test, logreg.predict_proba(X_test)[:, 1])\nconf_matrix = confusion_matrix(y_test, y_pred)\nclass_report = classification_report(y_test, y_pred, zero_division=0)\n\nprint('\\nAccuracy of logistic regression classifier on test set:', accuracy)\nprint('\\nROC AUC Score:', roc_auc)\nprint('\\nConfusion Matrix:\\n', conf_matrix)\nprint('\\nClassification Report:\\n', class_report)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nModel Coefficients:\nmanagement: 0.6481853859860419\nyear_started: -9.213405463801034e-05\nnations: -0.35032298993575\ngender_Male: 0.2724050540745125\ngender_Other, please specify: 0.5861371441624382\ngender_Prefer not to say: -0.27421545988671364\n\nAccuracy of logistic regression classifier on test set: 0.6363636363636364\n\nROC AUC Score: 0.5477168097548837\n\nConfusion Matrix:\n [[107  34]\n [ 38  19]]\n\nClassification Report:\n               precision    recall  f1-score   support\n\n           0       0.74      0.76      0.75       141\n           1       0.36      0.33      0.35        57\n\n    accuracy                           0.64       198\n   macro avg       0.55      0.55      0.55       198\nweighted avg       0.63      0.64      0.63       198\n\n```\n:::\n:::\n\n\n::: {#f0c6e4a8 .cell execution_count=13}\n``` {.python .cell-code}\n# Load the survey dataframe\nsurvey_clean = pd.read_pickle('data/tidied_survey.pkl')\n\n# Convert 'management' and 'online_teaching' from Yes/No to 0/1\nsurvey_clean['management'] = survey_clean['management'].map({'Yes': 1, 'No': 0})\nsurvey_clean['online_teaching'] = survey_clean['online_teaching'].map({'Yes': 1, 'No': 0})\n\n# Drop NA values only from the variables being tested\ncols_to_check = ['gender', 'management', 'online_teaching', 'year_started', 'nations']\nsurvey_clean = survey_clean.dropna(subset=cols_to_check)\n\n# One-hot encoding for 'gender'\ngender_encoder = OneHotEncoder(drop='first', sparse_output=False)\ngender_encoded = gender_encoder.fit_transform(survey_clean[['gender']])\ngender_encoded_df = pd.DataFrame(gender_encoded, columns=gender_encoder.get_feature_names_out(['gender']))\n\n# Join the encoded dataframe with the original dataframe\nsurvey_clean = survey_clean.reset_index(drop=True)  # Resetting index to ensure proper row alignment\nsurvey_clean = pd.concat([survey_clean, gender_encoded_df], axis=1)\n\n# Encoding 'nations' as numeric\nlabel_encoder = LabelEncoder()\nsurvey_clean['nations'] = label_encoder.fit_transform(survey_clean['nations'])\n\n# Convert 'year_started' to integer\nsurvey_clean['year_started'] = survey_clean['year_started'].astype(int)\n\n# Select only the relevant columns for the model\nfeature_cols = ['management', 'year_started', 'nations'] + list(gender_encoded_df.columns)\nX = survey_clean[feature_cols]\ny = survey_clean['online_teaching']\n\n# Splitting the dataset into training and test sets\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)\n\n# Handling NaN values using imputation\nimputer = SimpleImputer(strategy='mean')  # 'median' or 'most_frequent' is also possible\nX_train_imputed = imputer.fit_transform(X_train)\nX_test_imputed = imputer.transform(X_test)\n\n# Applying SMOTE to the imputed training set\nsmote = SMOTE(random_state=0)\nX_train_smote, y_train_smote = smote.fit_resample(X_train_imputed, y_train)\n\n# Build logistic regression model\nlogreg = LogisticRegression()\nlogreg.fit(X_train_smote, y_train_smote)\n\n# Predict test set results and calculate accuracy\ny_pred = logreg.predict(X_test_imputed)\n\n# Model Coefficients\nprint(\"\\nModel Coefficients:\")\nfor col, coef in zip(X_train.columns, logreg.coef_[0]):\n    print(f\"{col}: {coef}\")\n\n# Evaluation Metrics\naccuracy = logreg.score(X_test_imputed, y_test)\nroc_auc = roc_auc_score(y_test, logreg.predict_proba(X_test_imputed)[:, 1])\nconf_matrix = confusion_matrix(y_test, y_pred)\nclass_report = classification_report(y_test, y_pred, zero_division=0)\n\nprint('\\nAccuracy of logistic regression classifier on test set:', accuracy)\nprint('\\nROC AUC Score:', roc_auc)\nprint('\\nConfusion Matrix:\\n', conf_matrix)\nprint('\\nClassification Report:\\n', class_report)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nModel Coefficients:\nmanagement: 0.9335517522564059\nyear_started: -9.736589862979277e-05\nnations: -0.25970909109404616\ngender_Male: 0.32424847496990505\ngender_Other, please specify: 0.5927721979375616\ngender_Prefer not to say: -0.20961122277490868\n\nAccuracy of logistic regression classifier on test set: 0.6717171717171717\n\nROC AUC Score: 0.6486251088714694\n\nConfusion Matrix:\n [[101  40]\n [ 25  32]]\n\nClassification Report:\n               precision    recall  f1-score   support\n\n           0       0.80      0.72      0.76       141\n           1       0.44      0.56      0.50        57\n\n    accuracy                           0.67       198\n   macro avg       0.62      0.64      0.63       198\nweighted avg       0.70      0.67      0.68       198\n\n```\n:::\n:::\n\n\n# Conclusion\n\nBy putting people at the heart of research on technology, we have revealed hidden patterns in the data, the human stories behind the visualisations, and produced valuable insights which can inform how the world could change.\n\nThe findings suggest significant relationships between demographic and social factors and mindfulness teachers' technology usage, use of a professional website, and online teaching. This is crucial for understanding diverse needs in the digital landscape of mindfulness and wellness teaching. \n\nWe made some unexpected discoveries, finding statistically significant patterns.\n\n**Age** plays a contradictory role in this picture, where participants were relatively “early starters” to take advantage of the mindfulness trend, whilst also being vulnerable to a potentially widening digital divide.\n\nWebsite use and online teaching were significantly related to U.K. nation state contexts. Odds were more likely teachers would have professional websites and engage in online teaching in Wales and Scotland compared to England and Northern Ireland.\n\nYet, this is early days, and there is more analysis and research to be done.\n\nWe need to be careful when interpreting the findings of our survey. While likely representing the majority of mindfulness teachers who were active during 2017-2021, we used a convenience sample, with voluntary participation. This design is potentially subject to a self-selection bias, where those who responded might have different characteristics to those who did not reply. Our sample might not be representative of the wider U.K. population. In future research, we could situate our survey sample in relation to the U.K. population as a whole by integrating census data. This could be especially interesting for the geographical mapping.\n\nHow did mindfulness teachers weather the storm of the pandemic? We could investigate participants’ experiences of pivoting to digital work during COVID-19 pandemic.\n\nWe could also pay more in-depth attention the experiences of participants in the minority of our sample: people of colour, of diverse sexualities, with working class backgrounds. For example, our survey suggested that those reporting “Other” genders than male or female were potentially more likely to engage in online teaching and teach more students online. But our sample size was too small to draw any meaningful conclusions. We could explore these participants’ experiences in greater depth.\n\nBy putting people at the heart of the data revolution, we can reveal previously hidden inter-sectional patterns. In this case study, we showed how digital divides might result from differences in participants according to social structure - age, gender, ethnicity, social class.\n\nWe can use the tools of free and open science to make the findings of quantitative research, data analysis, and data science broadly accessible to a wide audience.\n\n",
    "supporting": [
      "mapmind_technology_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n<script>\nwindow.PlotlyConfig = {MathJaxConfig: 'local'};\nif (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}\n</script>\n<script type=\"module\">import \"https://cdn.plot.ly/plotly-3.4.0.min\"</script>\n\n"
      ]
    }
  }
}